### PR TITLE
CMake

### PR DESCRIPTION
**Pull request by maksw2**
Rotten to the core. There's no saving it -- we need to pull it out by the roots. 
Wipe the slate clean. BURN IT DOWN! And from the ashes, a new (build system) will be born.
 
Senator Armstrong

### CODE REVIEW

**Comment by maksw2** [comment]
@Sectonidse how are the shaders built?

**Comment by Sectonidse** [comment]
You can read the compiler here from line 125:
https://github.com/Sectonidse/SourceDEFUN/blob/master/materialsystem%2Fswarmshaders%2Fbuildshaders.bat

However, it doesn't build yet. It requies CMake project

I made the shader compilation a different job in Actions so fixing it would be much easier now

**Comment by maksw2** [comment]
so, to build shaders i just need to exec the script?

**Comment by Sectonidse** [comment]
yes

**Comment by maksw2** [comment]
should i include that?

**Comment by Sectonidse** [comment]
> should i include that?

no, i want compiling shaders to be separate from compiling a game

**Comment by maksw2** [comment]
cool, so it's mostly finished. still neeed to fix some errors generated by cmake and it'll be done.

**Comment by maksw2** [comment]
review changes and tell me what you think.

**Review by Sectonidse — APPROVED** [review]
Sorry for late response, i was experimenting with GMod's Lua scripting. 

I'm gonna merge this, but i think that Git might revert some new changes that your pull request doesn't have.

**Comment by maksw2** [comment]
github works on diffs, not the files. and since all i did is cmake it won't.

**Comment by maksw2** [comment]
it wasn't ready yet!

**Comment by Sectonidse** [comment]
> it wasn't ready yet!

I'm sorry, i realised that after merging. I didn't knew the button would make the pull request ready, i thought you prepared it. I'm giving you access to modify cmake branch directly.

**Pull request merged**
